version: '3.8'

services:
  portflick-backend:
    build: .
    image: portflick-backend:v1   
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - portflick-redis
    volumes:
      - .:/app
    restart: always

  portflick-redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
