version: '3.8'

services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
